// Drafts for the gig-fulfillment tool. A human pastes in a task description (sourced
// from wherever — Upwork, Fiverr, a direct client, an email), Claude drafts a
// deliverable, and the human reviews/edits it here before sending it anywhere
// themselves. This model never submits or sends the DELIVERABLE on its own —
// "delivered" just means the human marked it as done after doing that manually.
//
// The payment fields ARE a real financial side effect (2026-08-04): once a draft is
// delivered, requestPayment creates a real PayPal order — a payment LINK, not a
// charge — that the human sends to their client. Nothing is ever collected until the
// human explicitly confirms the client paid and this app calls PayPal's capture API.
const mongoose = require('mongoose');

const gigDraftSchema = new mongoose.Schema({
  taskType: {
    type: String,
    enum: ['writing', 'code', 'design-brief', 'website', 'pitch', 'other'],
    required: true
  },
  taskDescription: {
    type: String,
    required: true
  },
  draftContent: {
    type: String,
    required: true
  },
  // Set only if the human edits the draft in the review UI — draftContent stays the
  // original AI output, editedContent is what they actually intend to send.
  editedContent: {
    type: String
  },
  status: {
    type: String,
    enum: ['draft', 'delivered', 'discarded'],
    default: 'draft'
  },
  model: {
    type: String
  },
  // Set only when companyLeadHunterAgent generated this draft automatically for a
  // freshly discovered project lead, rather than a human pasting in a task. Always
  // still status 'draft' until a human reviews and marks it delivered — auto-drafting
  // skips the "click to draft" step, never the review step.
  autoGenerated: {
    type: Boolean,
    default: false
  },
  sourceOpportunityUrl: {
    type: String
  },
  paymentStatus: {
    // 'none': no payment requested yet.
    // 'pending': PayPal order created / crypto address issued, not yet received.
    // 'paid': funds have actually landed — PayPal capture or a matching on-chain deposit.
    // 'failed': PayPal capture was attempted and rejected (declined, expired, etc).
    type: String,
    enum: ['none', 'pending', 'paid', 'failed'],
    default: 'none'
  },
  // 'paypal' (default/legacy) or 'crypto' (2026-08-05) — which flow paymentStatus
  // below is tracking. Determines which fields are meaningful: paymentOrderId/
  // paymentApprovalUrl for paypal, paymentCrypto* for crypto.
  paymentMethod: {
    type: String,
    enum: ['paypal', 'crypto'],
    default: 'paypal'
  },
  paymentAmount: {
    type: Number
  },
  // For 'paypal': fiat code (USD/EUR/...). For 'crypto': the asset ticker (USDT/BTC),
  // duplicated into paymentCryptoAsset for clarity — paymentAmount is denominated
  // directly in this asset, not a USD-equivalent, so there's no exchange-rate
  // conversion/tolerance to get wrong.
  paymentCurrency: {
    type: String
  },
  paymentOrderId: {
    type: String
  },
  paymentApprovalUrl: {
    type: String
  },
  // PayPal capture ID (paymentMethod 'paypal') or the matched deposit's on-chain txId
  // (paymentMethod 'crypto') — either way, "the specific transaction that paid this."
  paymentCaptureId: {
    type: String
  },
  paymentCryptoAsset: {
    type: String
  },
  paymentCryptoNetwork: {
    type: String
  },
  paymentCryptoAddress: {
    type: String
  },
  // Memo/tag some coins require alongside the address (not needed for USDT-TRC20 or
  // BTC, kept for completeness if a future asset needs one).
  paymentCryptoTag: {
    type: String
  },
  // When the crypto request was created — deposits are only matched to this draft if
  // they arrived after this point, so an old, unrelated deposit to the same
  // (Binance-assigned, reused-across-requests) address can never be misattributed.
  paymentRequestedAt: {
    type: Date
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

gigDraftSchema.index({ createdAt: -1 });

module.exports = mongoose.model('GigDraft', gigDraftSchema);
